// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUserSessions = `-- name: CountActiveUserSessions :one
SELECT count(*)
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) CountActiveUserSessions(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id_hash, user_id, expires_at, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata
`

type CreateSessionParams struct {
	IDHash    string          `json:"id_hash"`
	UserID    string          `json:"user_id"`
	ExpiresAt time.Time       `json:"expires_at"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.IDHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= NOW()
   OR (revoked_at IS NOT NULL AND revoked_at <= NOW() - $1::interval)
`

// Cleanup job. Hard-deletes rows that are expired, or revoked more than
// $1::interval ago, so metadata doesn't accumulate forever.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, dollar_1 pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSessionByIDHash = `-- name: GetActiveSessionByIDHash :one
SELECT id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata
FROM sessions
WHERE id_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Valid = not revoked AND not expired. Used after hashing the cookie.
func (q *Queries) GetActiveSessionByIDHash(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByIDHash, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const getActiveSessionWithUserByIDHash = `-- name: GetActiveSessionWithUserByIDHash :one
SELECT
    s.id_hash,
    s.user_id,
    s.created_at,
    s.expires_at,
    s.revoked_at,
    s.last_seen,
    s.metadata,
    u.email,
    u.name,
    u.avatar_url,
    u.provider,
    u.provider_subject
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > NOW()
`

type GetActiveSessionWithUserByIDHashRow struct {
	IDHash          string          `json:"id_hash"`
	UserID          string          `json:"user_id"`
	CreatedAt       time.Time       `json:"created_at"`
	ExpiresAt       time.Time       `json:"expires_at"`
	RevokedAt       *time.Time      `json:"revoked_at"`
	LastSeen        time.Time       `json:"last_seen"`
	Metadata        json.RawMessage `json:"metadata"`
	Email           string          `json:"email"`
	Name            string          `json:"name"`
	AvatarUrl       *string         `json:"avatar_url"`
	Provider        string          `json:"provider"`
	ProviderSubject string          `json:"provider_subject"`
}

// Valid = not revoked AND not expired
// Joined to the user.
func (q *Queries) GetActiveSessionWithUserByIDHash(ctx context.Context, idHash string) (GetActiveSessionWithUserByIDHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionWithUserByIDHash, idHash)
	var i GetActiveSessionWithUserByIDHashRow
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
	)
	return i, err
}

const getSessionByIDHash = `-- name: GetSessionByIDHash :one
SELECT id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata FROM sessions
WHERE id_hash = $1
`

// Can be active / inactive session (expired / revoked)
func (q *Queries) GetSessionByIDHash(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByIDHash, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const listUserActiveSessions = `-- name: ListUserActiveSessions :many
SELECT
    id_hash,
    created_at,
    expires_at,
    last_seen,
    metadata
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY last_seen DESC
`

type ListUserActiveSessionsRow struct {
	IDHash    string          `json:"id_hash"`
	CreatedAt time.Time       `json:"created_at"`
	ExpiresAt time.Time       `json:"expires_at"`
	LastSeen  time.Time       `json:"last_seen"`
	Metadata  json.RawMessage `json:"metadata"`
}

// "Active sessions" UI. Returns live sessions only, newest first.
func (q *Queries) ListUserActiveSessions(ctx context.Context, userID string) ([]ListUserActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActiveSessionsRow{}
	for rows.Next() {
		var i ListUserActiveSessionsRow
		if err := rows.Scan(
			&i.IDHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastSeen,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// "Log out everywhere" / revoke all on password or privilege change.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByIDHash = `-- name: RevokeSessionByIDHash :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE id_hash = $1
  AND revoked_at IS NULL
`

// Logout for a single session. Soft revoke — keeps the audit trail in metadata.
func (q *Queries) RevokeSessionByIDHash(ctx context.Context, idHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByIDHash, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionsExceptCurrent = `-- name: RevokeUserSessionsExceptCurrent :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND id_hash <> $2
  AND revoked_at IS NULL
`

type RevokeUserSessionsExceptCurrentParams struct {
	UserID string `json:"user_id"`
	IDHash string `json:"id_hash"`
}

// Rotate on login: kill all other sessions, keep the one just created.
func (q *Queries) RevokeUserSessionsExceptCurrent(ctx context.Context, arg RevokeUserSessionsExceptCurrentParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionsExceptCurrent, arg.UserID, arg.IDHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :one
UPDATE sessions
SET last_seen = NOW()
WHERE id_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata
`

// Update activity without extending the absolute session lifetime.
// Call on authenticated requests only after a small application-level throttle.
func (q *Queries) TouchSessionLastSeen(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRow(ctx, touchSessionLastSeen, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}
