// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

// Hard delete. Sessions cascade via the FK. Prefer soft-delete / anonymize
// if you have audit or compliance requirements.
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

// Case-insensitive, matches users_email_idx. NOTE: email is unique, but a user
// may have one row per provider, so this can return multiple rows if you allow
// the same email across providers. If you do, switch to :many and reconcile.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndProvider = `-- name: GetUserByEmailAndProvider :one
SELECT id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
  AND provider = $2
`

type GetUserByEmailAndProviderParams struct {
	Lower    string `json:"lower"`
	Provider string `json:"provider"`
}

// Use this instead of GetUserByEmail when you want a single-identity lookup.
func (q *Queries) GetUserByEmailAndProvider(ctx context.Context, arg GetUserByEmailAndProviderParams) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailAndProviderStmt, getUserByEmailAndProvider, arg.Lower, arg.Provider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderSubject = `-- name: GetUserByProviderSubject :one
SELECT id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
FROM users
WHERE provider = $1
  AND provider_subject = $2
`

type GetUserByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

// Exact lookup on the identity key. Used when you already know the provider
// (e.g. re-authenticating a session whose provider you stored).
func (q *Queries) GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (User, error) {
	row := q.queryRow(ctx, q.getUserByProviderSubjectStmt, getUserByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
FROM users
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin listing. Keyset pagination on id is safer than OFFSET at scale.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Provider,
			&i.ProviderSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name       = $2,
    avatar_url = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

// Manual profile edit (name / avatar). Deliberately does NOT touch email or
// provider fields — those come from the IdP and would be overwritten on the
// next login anyway.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    email,
    name,
    avatar_url,
    provider,
    provider_subject
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (provider, provider_subject)
DO UPDATE SET
    email      = EXCLUDED.email,
    name       = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, email, name, avatar_url, provider, provider_subject, created_at, updated_at
`

type UpsertUserParams struct {
	Email           string         `json:"email"`
	Name            string         `json:"name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	Provider        string         `json:"provider"`
	ProviderSubject string         `json:"provider_subject"`
}

// The one query the OAuth callback actually needs. On first login it inserts;
// on every subsequent login it refreshes the mutable profile fields and returns
// the row. provider_subject is the conflict target — email is NOT, because
// emails change and a collision on email must not merge two identities.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.queryRow(ctx, q.upsertUserStmt, upsertUser,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
