// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countUserSessionsStmt, err = db.PrepareContext(ctx, countUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query CountUserSessions: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteExpiredSessionsStmt, err = db.PrepareContext(ctx, deleteExpiredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredSessions: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSessionWithUserStmt, err = db.PrepareContext(ctx, getSessionWithUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionWithUser: %w", err)
	}
	if q.listUserSessionsStmt, err = db.PrepareContext(ctx, listUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserSessions: %w", err)
	}
	if q.revokeSessionStmt, err = db.PrepareContext(ctx, revokeSession); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeSession: %w", err)
	}
	if q.revokeUserSessionsStmt, err = db.PrepareContext(ctx, revokeUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeUserSessions: %w", err)
	}
	if q.revokeUserSessionsExceptStmt, err = db.PrepareContext(ctx, revokeUserSessionsExcept); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeUserSessionsExcept: %w", err)
	}
	if q.touchSessionStmt, err = db.PrepareContext(ctx, touchSession); err != nil {
		return nil, fmt.Errorf("error preparing query TouchSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countUserSessionsStmt != nil {
		if cerr := q.countUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUserSessionsStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteExpiredSessionsStmt != nil {
		if cerr := q.deleteExpiredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredSessionsStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSessionWithUserStmt != nil {
		if cerr := q.getSessionWithUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionWithUserStmt: %w", cerr)
		}
	}
	if q.listUserSessionsStmt != nil {
		if cerr := q.listUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserSessionsStmt: %w", cerr)
		}
	}
	if q.revokeSessionStmt != nil {
		if cerr := q.revokeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeSessionStmt: %w", cerr)
		}
	}
	if q.revokeUserSessionsStmt != nil {
		if cerr := q.revokeUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeUserSessionsStmt: %w", cerr)
		}
	}
	if q.revokeUserSessionsExceptStmt != nil {
		if cerr := q.revokeUserSessionsExceptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeUserSessionsExceptStmt: %w", cerr)
		}
	}
	if q.touchSessionStmt != nil {
		if cerr := q.touchSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	countUserSessionsStmt        *sql.Stmt
	createSessionStmt            *sql.Stmt
	deleteExpiredSessionsStmt    *sql.Stmt
	getSessionStmt               *sql.Stmt
	getSessionWithUserStmt       *sql.Stmt
	listUserSessionsStmt         *sql.Stmt
	revokeSessionStmt            *sql.Stmt
	revokeUserSessionsStmt       *sql.Stmt
	revokeUserSessionsExceptStmt *sql.Stmt
	touchSessionStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		countUserSessionsStmt:        q.countUserSessionsStmt,
		createSessionStmt:            q.createSessionStmt,
		deleteExpiredSessionsStmt:    q.deleteExpiredSessionsStmt,
		getSessionStmt:               q.getSessionStmt,
		getSessionWithUserStmt:       q.getSessionWithUserStmt,
		listUserSessionsStmt:         q.listUserSessionsStmt,
		revokeSessionStmt:            q.revokeSessionStmt,
		revokeUserSessionsStmt:       q.revokeUserSessionsStmt,
		revokeUserSessionsExceptStmt: q.revokeUserSessionsExceptStmt,
		touchSessionStmt:             q.touchSessionStmt,
	}
}
