// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countUserSessions = `-- name: CountUserSessions :one
SELECT count(*)
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) CountUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.countUserSessionsStmt, countUserSessions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id_hash,
    user_id,
    expires_at,
    metadata
) VALUES (
    $1, $2, $3, $4
)
RETURNING id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata
`

type CreateSessionParams struct {
	IDHash    string          `json:"id_hash"`
	UserID    uuid.UUID       `json:"user_id"`
	ExpiresAt time.Time       `json:"expires_at"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.IDHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= NOW()
   OR (revoked_at IS NOT NULL AND revoked_at <= NOW() - $1::interval)
`

// Cleanup job. Hard-deletes rows that are expired, or revoked more than
// $1::interval ago, so metadata doesn't accumulate forever.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, dollar_1 int64) (int64, error) {
	result, err := q.exec(ctx, q.deleteExpiredSessionsStmt, deleteExpiredSessions, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id_hash, user_id, created_at, expires_at, revoked_at, last_seen, metadata
FROM sessions
WHERE id_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Valid = not revoked AND not expired. Use after hashing the cookie.
func (q *Queries) GetSession(ctx context.Context, idHash string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.id_hash,
    s.user_id,
    s.created_at,
    s.expires_at,
    s.revoked_at,
    s.last_seen,
    s.metadata,
    u.email,
    u.name,
    u.avatar_url,
    u.provider,
    u.provider_subject
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > NOW()
`

type GetSessionWithUserRow struct {
	IDHash          string          `json:"id_hash"`
	UserID          uuid.UUID       `json:"user_id"`
	CreatedAt       time.Time       `json:"created_at"`
	ExpiresAt       time.Time       `json:"expires_at"`
	RevokedAt       *time.Time      `json:"revoked_at"`
	LastSeen        time.Time       `json:"last_seen"`
	Metadata        json.RawMessage `json:"metadata"`
	Email           string          `json:"email"`
	Name            string          `json:"name"`
	AvatarUrl       sql.NullString  `json:"avatar_url"`
	Provider        string          `json:"provider"`
	ProviderSubject string          `json:"provider_subject"`
}

// Same validity rules, joined to the user so middleware can skip a second query.
func (q *Queries) GetSessionWithUser(ctx context.Context, idHash string) (GetSessionWithUserRow, error) {
	row := q.queryRow(ctx, q.getSessionWithUserStmt, getSessionWithUser, idHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeen,
		&i.Metadata,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    id_hash,
    created_at,
    expires_at,
    last_seen,
    metadata
FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY last_seen DESC
`

type ListUserSessionsRow struct {
	IDHash    string          `json:"id_hash"`
	CreatedAt time.Time       `json:"created_at"`
	ExpiresAt time.Time       `json:"expires_at"`
	LastSeen  time.Time       `json:"last_seen"`
	Metadata  json.RawMessage `json:"metadata"`
}

// "Active sessions" UI. Returns live sessions only, newest first.
func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.query(ctx, q.listUserSessionsStmt, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.IDHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastSeen,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE id_hash = $1
  AND revoked_at IS NULL
`

// Logout for a single session. Soft revoke — keeps the audit trail in metadata.
func (q *Queries) RevokeSession(ctx context.Context, idHash string) (int64, error) {
	result, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// "Log out everywhere" / revoke all on password or privilege change.
func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.revokeUserSessionsStmt, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUserSessionsExcept = `-- name: RevokeUserSessionsExcept :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND id_hash <> $2
  AND revoked_at IS NULL
`

type RevokeUserSessionsExceptParams struct {
	UserID uuid.UUID `json:"user_id"`
	IDHash string    `json:"id_hash"`
}

// Rotate on login: kill all other sessions, keep the one just created.
func (q *Queries) RevokeUserSessionsExcept(ctx context.Context, arg RevokeUserSessionsExceptParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeUserSessionsExceptStmt, revokeUserSessionsExcept, arg.UserID, arg.IDHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen  = NOW(),
    expires_at = NOW() + $2::interval
WHERE id_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type TouchSessionParams struct {
	IDHash  string `json:"id_hash"`
	Column2 int64  `json:"column_2"`
}

// Sliding renewal: bump last_seen and push expires_at forward.
// Call on authenticated requests, throttled (e.g. only if last_seen < now() - 1m).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.exec(ctx, q.touchSessionStmt, touchSession, arg.IDHash, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
